apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: test1                                 # FIXME
  region: ap-southeast-1                      # FIXME
  version: "1.21"

managedNodeGroups:
- name: ng-2
  instanceType: t3a.xlarge                    # FIXME; t3a.xlarge=4x16
  desiredCapacity: 1
  volumeSize: 80                              # FIXME
  ssh:
    allow: true
    publicKeyPath: ~/.ssh/id_rsa.pub

availabilityZones:
- ap-southeast-1a
- ap-southeast-1b
